[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "info"

# need to rebuild core because of nightly and alloc additionally because of the target 
# https://stackoverflow.com/a/72654343
[unstable]
build-std = ["core", "alloc"]