version: 2
updates:
  - package-ecosystem: cargo
    directory: /gateway-host-schema
    schedule:
      interval: daily
  
  - package-ecosystem: cargo
    directory: /module-gateway
    schedule:
      interval: daily
  
  - package-ecosystem: cargo
    directory: /module-node
    schedule:
      interval: daily
  
  - package-ecosystem: cargo
    directory: /module-runtime
    schedule:
      interval: daily

  - package-ecosystem: cargo
    directory: /module-bootloader
    schedule:
      interval: daily
  
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
